### 一覧取得
GET http://localhost:8080/records

### 詳細取得
GET http://localhost:8080/records/1

### 登録
POST http://localhost:8080/records
Content-Type: application/json

{
  "studyDate": "2026-06-09",
  "studyContent": "更新前データ",
  "studyHours": 3
}

### 更新
PUT http://localhost:8080/records/1
Content-Type: application/json

{
  "studyDate": "2026-06-10",
  "studyContent": "更新テスト",
  "studyHours": 10
}

### 削除
DELETE http://localhost:8080/records/1